// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParksAPI.Models;

#nullable disable

namespace NationalParksApi.Migrations
{
    [DbContext(typeof(NationalParkContext))]
    partial class NationalParkContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ParksAPI.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ParkDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("ParkLocation")
                        .HasColumnType("longtext");

                    b.Property<string>("ParkName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ParkSize")
                        .HasColumnType("longtext");

                    b.Property<string>("ParkType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            ParkDescription = "a Massive park",
                            ParkLocation = "Wyoming",
                            ParkName = "Yellowstone",
                            ParkSize = "2.2 million acres",
                            ParkType = "National"
                        },
                        new
                        {
                            ParkId = 2,
                            ParkDescription = "A lot of really tall trees",
                            ParkLocation = "California",
                            ParkName = "Sequoia and Kings Canyon",
                            ParkSize = "1353 square miles",
                            ParkType = "National"
                        },
                        new
                        {
                            ParkId = 3,
                            ParkDescription = "Awesome rock formations",
                            ParkLocation = "Nevada",
                            ParkName = "Valley of Fire",
                            ParkSize = "40,000 acres",
                            ParkType = "State"
                        },
                        new
                        {
                            ParkId = 4,
                            ParkDescription = "A good place to Hike with a fantastic waterfall at the end.",
                            ParkLocation = "West Virginia",
                            ParkName = "Blackwater Falls",
                            ParkSize = "2,358 acres",
                            ParkType = "State"
                        },
                        new
                        {
                            ParkId = 5,
                            ParkDescription = "The biggest water park in the United States!",
                            ParkLocation = "Wisconsin",
                            ParkName = "Noah's Ark",
                            ParkSize = "70 acres",
                            ParkType = "Water Park"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
